using System;
using System.Collections.Generic;

namespace FFXIV.Packets
{
    public class WorldS2CPlayerSetup : OpcodePacket
    {
        public UInt64 contentId;
        public UInt32 unknown8;
        public UInt32 unknownC;
        public UInt32 charId;
        public UInt32 restedExp;
        public UInt32 companionCurrentExp;
        public UInt32 unknown1C;
        public UInt32 fishCaught;
        public UInt32 useBaitCatalogId;
        public UInt32 unknown28;
        public UInt16 unknownPvp2C;
        public UInt16 unknown3;
        public UInt32 pvpFrontlineOverallCampaigns;
        public UInt32 unknownTimestamp34;
        public UInt32 unknownTimestamp38;
        public UInt32 unknown3C;
        public UInt32 unknown40;
        public UInt32 unknown44;
        public Single companionTimePassed;
        public UInt32 unknown4C;
        public UInt16 unknown50;
        public List<UInt16> unknownPvp = new List<UInt16>(new UInt16[4]);
        public UInt16 playerCommendations;
        public UInt16 unknown5C;
        public UInt16 unknown5E;
        public UInt16 pvpFrontlineWeeklyCampaigns;
        public UInt16 enhancedAnimaGlassProgress;
        public List<UInt16> unknown64 = new List<UInt16>(new UInt16[4]);
        public UInt16 pvpRivalWingsTotalMatches;
        public UInt16 pvpRivalWingsTotalVictories;
        public UInt16 pvpRivalWingsWeeklyMatches;
        public UInt16 pvpRivalWingsWeeklyVictories;
        public Byte maxLevel;
        public Byte expansion;
        public Byte unknown76;
        public Byte race;
        public Byte tribe;
        public Byte gender;
        public Byte unknown7A;
        public Byte currentJob;
        public Byte currentClass;
        public Byte deity;
        public Byte namedayMonth;
        public Byte namedayDay;
        public Byte cityState;
        public Byte homepoint;
        public Byte unknown82;
        public Byte petHotBar;
        public Byte companionRank;
        public Byte companionStars;
        public Byte companionSp;
        public Byte companionUnk86;
        public Byte companionColor;
        public Byte companionFavoFeed;
        public Byte unknown89;
        public List<Byte> unknown8A = new List<Byte>(new Byte[4]);
        public Byte hasRelicBook;
        public Byte relicBookId;
        public List<Byte> unknown90 = new List<Byte>(new Byte[4]);
        public Byte craftingMasterMask;
        public List<Byte> unknown95 = new List<Byte>(new Byte[14]);
        public List<UInt32> exp = new List<UInt32>(new UInt32[28]); // per job
        public UInt32 unknown108;
        public UInt32 pvpTotalExp;
        public UInt32 unknownPvp110;
        public UInt32 pvpExp;
        public List<UInt32> pvpFrontlineOverallRanks = new List<UInt32>(new UInt32[3]);
        public List<UInt16> levels = new List<UInt16>(new UInt16[28]); // per job
        public List<UInt16> unknown15C = new List<UInt16>(new UInt16[9]);
        public UInt16 u1;
        public UInt16 u2;
        public List<UInt16> unknown112 = new List<UInt16>(new UInt16[23]);
        public List<UInt16> fishingRecordsFish = new List<UInt16>(new UInt16[26]);
        public List<UInt16> beastExp = new List<UInt16>(new UInt16[11]);
        public List<UInt16> unknown1EA = new List<UInt16>(new UInt16[5]);
        public List<UInt16> pvpFrontlineWeeklyRanks = new List<UInt16>(new UInt16[3]);
        public List<UInt16> unknownMask1FA = new List<UInt16>(new UInt16[4]);
        public String companionName = new String(' ', 21);
        public Byte companionDefRank;
        public Byte companionAttRank;
        public Byte companionHealRank;
        public UInt16 u19;
        public List<Byte> mountGuideMask = new List<Byte>(new Byte[19]);
        public String name = new String(' ', 32);
        public List<Byte> unknownOword = new List<Byte>(new Byte[16]);
        public Byte unknownOw;
        public List<Byte> unlockBitmask = new List<Byte>(new Byte[64]);
        public List<Byte> aetheryte = new List<Byte>(new Byte[21]);
        public List<Byte> discovery = new List<Byte>(new Byte[445]);
        public List<Byte> howto = new List<Byte>(new Byte[34]);
        public List<Byte> minions = new List<Byte>(new Byte[45]);
        public List<Byte> chocoboTaxiMask = new List<Byte>(new Byte[10]);
        public List<Byte> watchedCutscenes = new List<Byte>(new Byte[124]);
        public List<Byte> companionBardingMask = new List<Byte>(new Byte[10]);
        public Byte companionEquippedHead;
        public Byte companionEquippedBody;
        public Byte companionEquippedLegs;
        public List<Byte> unknown52A = new List<Byte>(new Byte[4]);
        public List<Byte> unknownMask52E = new List<Byte>(new Byte[11]);
        public List<Byte> fishingGuideMask = new List<Byte>(new Byte[105]);
        public List<Byte> fishingSpotVisited = new List<Byte>(new Byte[31]);
        public List<Byte> unknown59A = new List<Byte>(new Byte[27]);
        public List<Byte> unknown5A9 = new List<Byte>(new Byte[7]);
        public List<Byte> beastRank = new List<Byte>(new Byte[11]);
        public List<Byte> unknownPvp5AB = new List<Byte>(new Byte[11]);
        public List<Byte> unknown5B9 = new List<Byte>(new Byte[5]);
        public Byte pose;
        public Byte unknown5B91;
        public List<Byte> challengeLogComplete = new List<Byte>(new Byte[9]);
        public Byte weaponPose;
        public List<Byte> unknownMask673 = new List<Byte>(new Byte[10]);
        public List<Byte> unknownMask5DD = new List<Byte>(new Byte[28]);
        public List<Byte> relicCompletion = new List<Byte>(new Byte[12]);
        public List<Byte> sightseeingMask = new List<Byte>(new Byte[26]);
        public List<Byte> huntingMarkMask = new List<Byte>(new Byte[55]);
        public List<Byte> tripleTriadCards = new List<Byte>(new Byte[32]);
        public List<Byte> u12 = new List<Byte>(new Byte[11]);
        public Byte u13;
        public List<Byte> aetherCurrentMask = new List<Byte>(new Byte[22]);
        public List<Byte> u10 = new List<Byte>(new Byte[3]);
        public List<Byte> orchestrionMask = new List<Byte>(new Byte[40]);
        public List<Byte> hallOfNoviceCompletion = new List<Byte>(new Byte[3]);
        public List<Byte> animaCompletion = new List<Byte>(new Byte[11]);
        public List<Byte> u14 = new List<Byte>(new Byte[16]);
        public List<Byte> u15 = new List<Byte>(new Byte[13]);
        public List<Byte> unlockedRaids = new List<Byte>(new Byte[28]);
        public List<Byte> unlockedDungeons = new List<Byte>(new Byte[18]);
        public List<Byte> unlockedGuildhests = new List<Byte>(new Byte[10]);
        public List<Byte> unlockedTrials = new List<Byte>(new Byte[8]);
        public List<Byte> unlockedPvp = new List<Byte>(new Byte[5]);
        public List<Byte> clearedRaids = new List<Byte>(new Byte[28]);
        public List<Byte> clearedDungeons = new List<Byte>(new Byte[18]);
        public List<Byte> clearedGuildhests = new List<Byte>(new Byte[10]);
        public List<Byte> clearedTrials = new List<Byte>(new Byte[8]);
        public List<Byte> clearedPvp = new List<Byte>(new Byte[5]);
        public List<UInt16> fishingRecordsFishWeight = new List<UInt16>(new UInt16[26]);
        public UInt32 exploratoryMissionNextTimestamp;
        public Byte pvpLevel;
    }
}
